const ENDPOINTS = {
  clinicalAreas: "/custom/clinical_areas",
  customConditions: "/custom/conditions",
  conditions: "/conditions",
  conditionCostEstimate: "/condition_cost_estimate",
  insurances: "/insurances",
  customInsurances: "/custom/insurances",
  languages: "/languages",
  locations: "/custom/locations",
  customLocations: "/locations",
  locationTypes: "/location_types",
  customLocationTypes: "/custom/location_types",
  organizations: "/custom/organizations",
  procedures: "/procedures",
  customProcedures: "/custom/procedures",
  procedureCostEstimates: "/procedure_cost_estimate",
  providers: "/custom/providers",
  providerTypes: "/provider_types",
  customProviderTypes: "/custom/provider_types",
  specialties: "/specialties",
  customSpecialties: "/custom/specialties",
  treatments: "/custom/treatments",
};

export default ENDPOINTS;
